# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5034288a21ef139fbcc2823f68719e41cd326c3d7b3f9b81163d192e9b0aea9f0ac6abb1e52543c31ccfb876c26288ca3729972bebf0ab92e8edcbea42345e0f

test:
  secret_key_base: c31035e25e394a23386dd58da7d016ce678d19697ddf67b55556a1a904b5d0ba9213fa02e1888ce5a2a0d6da85e0e09d36215a508d7c8f71103d45cd89d9baac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
